package main.java.backend.model;

public enum WeatherConditions {
    CLEAR_SKY, CLOUDY, FOG, DRIZZLE,
    FREEZING_DRIZZLE, RAIN, FREEZING_RAIN,
    SNOW_FALL, SNOW_GRAINS, RAIN_SHOWERS,
    SNOW_SHOWERS, THUNDERSTORM, HAIL_THUNDERSTORM,
    UNIDENTIFIED
}
